en:
  errors:
    token_ok?: 'Token.already.confirmed'
    token_expired?: 'Token.invalid.or.expired'
    unique_title?: 'Post.title.not.unique'
    article_10_words?: 'Post.article.less.than.10.words'
    article_2_lines?: 'Post.article.less.than.2.lines'
    category_exists?: 'Post.category.does.not.exists'
    unique_name?: 'Registration.sign_up.name.not.unique'
    unique_email?: 'Registration.sign_up.email.not.unique'
    password_strong?: 'Registration.sign_up.password.weak'
    token_confirmed?: 'Registration.confirmation.already.confirmed'
    token_invalid?: 'Registration.confirmation.token.invalid'
    date_of_birth_ok?: 'Profile.date_of_birth.not_a_date'
    file_size_ok?: 'File.wrong.size'
    file_type_ok?: 'File.wrong.type'
    password_ok?: 'Session.sign_in.password.not.ok'
    valid_email?: 'Session.sign_in.no.valid.email'
    category_not_used?: 'Category.still.used.in.post'
    category_childs_not_used?: 'Category.child.still.used.in.post'