:post:
  :types:
    -
      :name: :published
      :type: 'Virtus::Attribute::Boolean'
    -
      :name: :published_on
      :type: 'Date'
    -
      :name: :comments
      :type: 'String'
:blog:
  :inherit: :post