:post:
  :types:
    -
      :name: :published
      :type: 'Types::Form::Bool'
      :default: 'false'
    -
      :name: :published_on
      :type: 'Types::Form::DateTime'
    -
      :name: :comments
      :type: 'Types::Coercible::String'
:blog:
  :inherit: :post